/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/scene.gltf --legacy-peer-deps
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cube-cascade-11ba2667998d45f8b3ad178b27a34725
Title: Cube Cascade
*/

import React, {useRef} from 'react';
import {useGLTF, useAnimations} from '@react-three/drei';

export default function Model(props) {
	const group = useRef();
	const {nodes, materials, animations} = useGLTF('./models/scene.gltf');
	const {actions} = useAnimations(animations, group);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name='Sketchfab_Scene'>
				<group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]}>
					<group name='root'>
						<group name='GLTF_SceneRootNode' rotation={[Math.PI / 2, 0, 0]}>
							<group name='Cube_0'>
								<mesh name='Object_4' geometry={nodes.Object_4.geometry} material={materials.material} />
							</group>
							<group name='Cube001_1' scale={0.79}>
								<mesh name='Object_6' geometry={nodes.Object_6.geometry} material={materials.material_1} />
							</group>
							<group name='Cube002_2' scale={0.63}>
								<mesh name='Object_8' geometry={nodes.Object_8.geometry} material={materials.material_2} />
							</group>
							<group name='Cube003_3' scale={0.49}>
								<mesh name='Object_10' geometry={nodes.Object_10.geometry} material={materials.material_3} />
							</group>
							<group name='Cube004_4' scale={0.37}>
								<mesh name='Object_12' geometry={nodes.Object_12.geometry} material={materials.material_4} />
							</group>
							<group name='Cube005_5' scale={0.28}>
								<mesh name='Object_14' geometry={nodes.Object_14.geometry} material={materials.material_5} />
							</group>
							<group name='Cube006_6' scale={0.2}>
								<mesh name='Object_16' geometry={nodes.Object_16.geometry} material={materials.material_6} />
							</group>
							<group name='Cube007_7' scale={0.14}>
								<mesh name='Object_18' geometry={nodes.Object_18.geometry} material={materials.material_7} />
							</group>
							<group name='Cube008_8' scale={0.09}>
								<mesh name='Object_20' geometry={nodes.Object_20.geometry} material={materials.material_8} />
							</group>
							<group name='Cube009_9' scale={0.05}>
								<mesh name='Object_22' geometry={nodes.Object_22.geometry} material={materials.material_9} />
							</group>
							<group name='Cube010_10' scale={0.03}>
								<mesh name='Object_24' geometry={nodes.Object_24.geometry} material={materials.material_10} />
							</group>
							<group name='Circle_11' scale={1.85} />
						</group>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('./models/scene.gltf');
